### PR TITLE
Apply the latest charm template

### PR DESCRIPTION
**Pull request by agileshaw**

### CODE REVIEW

**Review by rgildein — APPROVED** [review]
LGTM

**Comment by mkalcok** [comment]
I don't have any objections here, so +1. But I think we should consider naming of `integration` tests vs `functional`. `charmcraft init` generates template with `integration` tests. I think we should conform to this naming.

**Review by mkalcok — APPROVED** [review]

**Comment by rgildein** [comment]
> I don't have any objections here, so +1. But I think we should consider naming of `integration` tests vs `functional`. `charmcraft init` generates template with `integration` tests. I think we should conform to this naming.

Can you introduce this in our templates? I'm +1 to have it uniformed with `charmcraft init`.

**Comment by agileshaw** [comment]
> > I don't have any objections here, so +1. But I think we should consider naming of `integration` tests vs `functional`. `charmcraft init` generates template with `integration` tests. I think we should conform to this naming.
> 
> Can you introduce this in our templates? I'm +1 to have it uniformed with `charmcraft init`.

@rgildein Yes, this is still on my radar. I will open another PR once I update the template

**Pull request merged**
